apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Backend Configuration
  SPRING_PROFILES_ACTIVE: "azure"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://acrtestlatest-pg.postgres.database.azure.com:5432/testlatest_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SERVER_PORT: "8080"
  
  # Frontend Configuration
  BACKEND_API_URL: "https://testlatest-backend.eastus.azurecontainerapps.io"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: acrtestlatest.azurecr.io/testlatest-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: acrtestlatest.azurecr.io/testlatest-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_API_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5173
  type: LoadBalancer 